# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KoTDKdwaRayJSeN2FcW5QFal84DjuRQ
"""

# Initialize Gemini Client using API key from Streamlit secrets
gemini_api_key = st.secrets["gemini_api_key"]
gmn_client = genai.Client(api_key=gemini_api_key)

# Function to generate response from Gemini
def generate_gemini_answer(prompt):
    try:
        response = gmn_client.models.generate_content(
            model='gemini-2.5-flash-lite',
            contents=prompt
        )
        return response.text
    except Exception as e:
        return f"Error during Gemini text generation: {e}"

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

st.title("Gemini Chat Test")

# Display chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Chat input
if prompt := st.chat_input("Message to Gemini..."):

    # 1. Save user message
    st.session_state.messages.append({
        "role": "user",
        "content": prompt
    })

    # 2. Display user message
    with st.chat_message("user"):
        st.markdown(prompt)

    # 3. Generate and display assistant response
    with st.chat_message("assistant"):
        response = generate_gemini_answer(prompt)
        st.markdown(response)

    # 4. Save assistant response
    st.session_state.messages.append({
        "role": "assistant",
        "content": response
    })